name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'lexicalresources'
      - run: pwd
      - run: ls
      - run: curl https://jenkins.tei-c.org/view/TEI%20dev/job/Stylesheets-dev/lastStableBuild/artifact/tei-xsl-7.50.0a.zip -L -o styesheets.zip
      - run: ls
      - run: unzip styesheets.zip
      - run: cd styesheets
      - run: ls
